### ISSUE TITLE
Annealing Schedule

### ISSUE THREAD

**Issue by csvance** [Jeff-sjtu/sampling-argmax#2]
Hello, the paper mentions you use an annealing schedule going from high to low temperature. In the review its mentioned how the method is parameter free, I take it you found a single annealing schedule that worked effectively for the temperature during training? I was wondering since the code is not published yet if you could provide the schedule you used. 

On a side note it's great to see more research on soft-argmax! Thank you to all of the authors :clap:

**Comment by jeffffffli** [comment]
Hi @csvance, our code is now released.
