### ISSUE TITLE
I wonder why "training with only sample outperforms soft-argmax"

### ISSUE THREAD

**Issue by Indigo6** [Jeff-sjtu/sampling-argmax#3]
Thanks for your great work!
I've just read your paper and the discussions on _OpenReview_, and have the same question with the reviewer——

Although it's indicated in "We conduct an experiment of training the model with Eq. 5. The model only obtains 30.9 mAP on COCO Keypoint" that training with discrete density map can not work, I still wonder why sampling (works) and why "training with only sample outperforms soft-argmax"

**Comment by jeffffffli** [comment]
Hi @Indigo6, training with only one sample is still an approximation of "the expectation of the error", and can impose the shape constraint on the predicted heatmap.
